# Teori
kNN merupakan algoritma klasifikasi yang paling sederhana. Sebuah data baru diklasifikasikan ke dalam kelas yang paling mendominasi dari K tetangga data terdekatnya. K tetangga terdekat didefinisikan sebagai K data sampel dengan jarak terdekat dengan data baru. 

Berikut merupakan tahapan dari algoritma kNN: 
1. Tentukan parameter `K`, yaitu bilangan bulat positif yang menyatakan jumlah tetangga terdekat.
2. Hitung jarak data baru ke seluruh data sampel. Penghitungan jarak dapat menggunakan salah satu dari ketiga metode berikut:
   - Euclidian Distance

     <img src="assets/euclid.png">
   - City Block/Manhattan Distance

     <img src="assets/city.png">
   - Minkowski

     <img src="assets/minkowski.png">
3. Urutkan data sampel berdasarkan jaraknya (dari terdekat ke terjauh) ke data baru. Tentukan pula K data sampel dengan jarak terdekat (tetangga terdekat).
4. Kelompokkan K tetangga terdekat tersebut berdasarkan atribut kelasnya.
5. Data baru diklasifikasikan ke dalam kelas dengan jumlah tentangga terdekat paling banyak (mayoritas).

# Praktek

## 0) Info Dataset

1. Title of Database: MAGIC gamma telescope data 2004

2. Sources:

   (a) Original owner of the database:

       R. K. Bock
       Major Atmospheric Gamma Imaging Cherenkov Telescope project (MAGIC)
       http://wwwmagic.mppmu.mpg.de
       rkb@mail.cern.ch

   (b) Donor:

       P. Savicky
       Institute of Computer Science, AS of CR
       Czech Republic
       savicky@cs.cas.cz

   (c) Date received: May 2007

3. Past Usage:

   (a) Bock, R.K., Chilingarian, A., Gaug, M., Hakl, F., Hengstebeck, T.,
       Jirina, M., Klaschka, J., Kotrc, E., Savicky, P., Towers, S.,
       Vaicilius, A., Wittek W. (2004).
       Methods for multidimensional event classification: a case study
       using images from a Cherenkov gamma-ray telescope.
       Nucl.Instr.Meth. A, 516, pp. 511-528.

   (b) P. Savicky, E. Kotrc.
       Experimental Study of Leaf Confidences for Random Forest.
       Proceedings of COMPSTAT 2004, In: Computational Statistics.
       (Ed.: Antoch J.) - Heidelberg, Physica Verlag 2004, pp. 1767-1774.

   (c) J. Dvorak, P. Savicky.
       Softening Splits in Decision Trees Using Simulated Annealing.
       Proceedings of ICANNGA 2007, Warsaw, (Ed.: Beliczynski et. al),
       Part I, LNCS 4431, pp. 721-729.

4. Relevant Information:

   The data are MC generated (see below) to simulate registration of high energy
   gamma particles in a ground-based atmospheric Cherenkov gamma telescope using the
   imaging technique. Cherenkov gamma telescope observes high energy gamma rays,
   taking advantage of the radiation emitted by charged particles produced
   inside the electromagnetic showers initiated by the gammas, and developing in the
   atmosphere. This Cherenkov radiation (of visible to UV wavelengths) leaks
   through the atmosphere and gets recorded in the detector, allowing reconstruction
   of the shower parameters. The available information consists of pulses left by
   the incoming Cherenkov photons on the photomultiplier tubes, arranged in a
   plane, the camera. Depending on the energy of the primary gamma, a total of
   few hundreds to some 10000 Cherenkov photons get collected, in patterns
   (called the shower image), allowing to discriminate statistically those
   caused by primary gammas (signal) from the images of hadronic showers
   initiated by cosmic rays in the upper atmosphere (background).

   Typically, the image of a shower after some pre-processing is an elongated
   cluster. Its long axis is oriented towards the camera center if the shower axis
   is parallel to the telescope's optical axis, i.e. if the telescope axis is
   directed towards a point source. A principal component analysis is performed
   in the camera plane, which results in a correlation axis and defines an ellipse.
   If the depositions were distributed as a bivariate Gaussian, this would be
   an equidensity ellipse. The characteristic parameters of this ellipse
   (often called Hillas parameters) are among the image parameters that can be
   used for discrimination. The energy depositions are typically asymmetric
   along the major axis, and this asymmetry can also be used in discrimination.
   There are, in addition, further discriminating characteristics, like the
   extent of the cluster in the image plane, or the total sum of depositions.

   The data set was generated by a Monte Carlo program, Corsika, described in 
      D. Heck et al., CORSIKA, A Monte Carlo code to simulate extensive air showers,
      Forschungszentrum Karlsruhe FZKA 6019 (1998).
   The program was run with parameters allowing to observe events with energies down
   to below 50 GeV.

5. Number of Instances: 19020

6. Number of Attributes: 11 (including the class)

7. Attribute information:

    1.  fLength:  continuous  # major axis of ellipse [mm]
    2.  fWidth:   continuous  # minor axis of ellipse [mm] 
    3.  fSize:    continuous  # 10-log of sum of content of all pixels [in #phot]
    4.  fConc:    continuous  # ratio of sum of two highest pixels over fSize  [ratio]
    5.  fConc1:   continuous  # ratio of highest pixel over fSize  [ratio]
    6.  fAsym:    continuous  # distance from highest pixel to center, projected onto major axis [mm]
    7.  fM3Long:  continuous  # 3rd root of third moment along major axis  [mm] 
    8.  fM3Trans: continuous  # 3rd root of third moment along minor axis  [mm]
    9.  fAlpha:   continuous  # angle of major axis with vector to origin [deg]
   10.  fDist:    continuous  # distance from origin to center of ellipse [mm]
   11.  class:    g,h         # gamma (signal), hadron (background)

8. Missing Attribute Values: None

9. Class Distribution:

   g = gamma (signal):     12332
   h = hadron (background): 6688

   For technical reasons, the number of h events is underestimated.
   In the real data, the h class represents the majority of the events.

   The simple classification accuracy is not meaningful for this data, since
   classifying a background event as signal is worse than classifying a signal
   event as background. For comparison of different classifiers an ROC curve
   has to be used. The relevant points on this curve are those, where the
   probability of accepting a background event as signal is below one of the
   following thresholds: 0.01, 0.02, 0.05, 0.1, 0.2 depending on the required
   quality of the sample of the accepted events for different experiments.

## 1) Mengimpor Library

In [19]:
import pandas as pd
import numpy as np
import copy
from sklearn.preprocessing import StandardScaler
from IPython.display import display

In [24]:
# Sample points
point1 = np.array([1, 2])
point2 = np.array([4, 6])

# Calculate Euclidean distance
distance = np.linalg.norm(point1 - point2)

print(distance)

5.0

## 2) Memuat Dataset

In [71]:
# Loading the UC Magic Gamma Dataset
cols = ["fLength", "fWidth", "fSize", "fConc", "fConc1", "fAsym", "fM3Long", "fM3Trans", "fAlpha", "fDist", "class"]
df = pd.read_csv("dataset/magic04.data", names=cols)
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19020 entries, 0 to 19019
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   fLength   19020 non-null  float64
 1   fWidth    19020 non-null  float64
 2   fSize     19020 non-null  float64
 3   fConc     19020 non-null  float64
 4   fConc1    19020 non-null  float64
 5   fAsym     19020 non-null  float64
 6   fM3Long   19020 non-null  float64
 7   fM3Trans  19020 non-null  float64
 8   fAlpha    19020 non-null  float64
 9   fDist     19020 non-null  float64
 10  class     19020 non-null  object
dtypes: float64(10), object(1)
memory usage: 1.6+ MB
None

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,g
1,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
2,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
3,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
4,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g

In [72]:
# Calculating the class distribution
df['class'].value_counts()

class
g    12332
h     6688
Name: count, dtype: int64

In [18]:
# Basic Info
df.describe()

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist
count,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000
mean,53.250154,22.180966,2.825017,0.380327,0.214657,-4.331745,10.545545,0.249726,27.645707,193.818026
std,42.364855,18.346056,0.472599,0.182813,0.110511,59.206062,51.000118,20.827439,26.103621,74.731787
min,4.283500,0.000000,1.941300,0.013100,0.000300,-457.916100,-331.780000,-205.894700,0.000000,1.282600
25%,24.336000,11.863800,2.477100,0.235800,0.128475,-20.586550,-12.842775,-10.849375,5.547925,142.492250
50%,37.147700,17.139900,2.739600,0.354150,0.196500,4.013050,15.314100,0.666200,17.679500,191.851450
75%,70.122175,24.739475,3.101600,0.503700,0.285225,24.063700,35.837800,10.946425,45.883550,240.563825
max,334.177000,256.382000,5.323300,0.893000,0.675200,575.240700,238.321000,179.851000,90.000000,495.561000

In [50]:
sample = df.iloc[0, :-1].values
print(sample)
df.iloc[0]

[28.7967 16.0021 2.6449 0.3918 0.1982 27.7004 22.011 -8.2027 40.092
 81.8828 0.0]

fLength      28.7967
fWidth       16.0021
fSize         2.6449
fConc         0.3918
fConc1        0.1982
fAsym        27.7004
fM3Long       22.011
fM3Trans     -8.2027
fAlpha        40.092
fDist        81.8828
Distances        0.0
class              g
Name: 0, dtype: object

In [51]:
features = df[df.columns[:-1]].values
features

array([[ 28.7967    ,  16.0021    ,   2.6449    , ...,  40.092     ,
         81.8828    ,   0.        ],
       [ 31.6036    ,  11.7235    ,   2.5185    , ...,   6.3609    ,
        205.261     , 128.04149583],
       [162.052     , 136.031     ,   4.0612    , ...,  76.96      ,
        256.788     , 284.53750181],
       ...,
       [ 75.4455    ,  47.5305    ,   3.4483    , ...,  30.2987    ,
        256.5166    , 188.41775972],
       [120.5135    ,  76.9018    ,   3.9939    , ...,  84.6874    ,
        408.3166    , 370.93562505],
       [187.1814    ,  53.0014    ,   3.2093    , ...,  52.731     ,
        272.3174    , 372.50780741]])

In [35]:
distances = []
for x in features:
    distances.append(np.linalg.norm(x - sample))
distances

[0.0,
 128.04149583322587,
 284.5375018093221,
 54.51574300410845,
 284.7272625790337,
 166.10785141347174,
 146.3865289331638,
 160.27753132120546,
 218.72145929375563,
 47.59534410055252,
 257.9250423397852,
 91.49968496169811,
 123.1865387557017,
 74.96896577958108,
 302.4548489336549,
 134.6936684863472,
 129.4831945367815,
 31.534849542054268,
 109.75508779929064,
 148.43609998059773,
 251.71025040128978,
 249.665545432084,
 230.4847622826073,
 22.900144826834605,
 277.24879753843845,
 250.77944487148466,
 47.55987737957279,
 29.707568020960586,
 110.50910685332678,
 65.39097440320032,
 69.67955554364566,
 303.1076265329858,
 83.21382591613005,
 134.12368811932512,
 229.0176314226265,
 201.68281112241567,
 98.19003893002588,
 63.09801974388736,
 104.38408083754918,
 307.41154777317655,
 234.4360517406826,
 97.43819453161063,
 144.84420871505358,
 48.17554896760389,
 165.8065575156785,
 57.94271842811657,
 115.51219877450173,
 93.4631185237792,
 237.81561875398344,
 99.53861051722592,
 128.71041233835746,
 146.45649886874259,
 235.96070791496197,
 195.77427576696587,
 91.66112893315247,
 242.23487990328724,
 75.48332682301435,
 288.85017047199403,
 207.38028163089666,
 74.27624590991388,
 156.94200011497878,
 125.20608131704304,
 111.47558510135752,
 164.12033392154672,
 250.60613993226505,
 83.489927428403,
 90.88684163656475,
 90.1890091668048,
 128.1800009113356,
 145.40381723135744,
 144.19990868096968,
 97.67850711108355,
 128.69477770426428,
 127.53823927563842,
 56.28079961194581,
 149.3711492760901,
 171.65155015789983,
 289.0842836444244,
 247.03865759455545,
 126.56022787040958,
 144.80809995846226,
 132.80143622288125,
 89.27317553167916,
 66.6210948665661,
 32.56288785688394,
 207.8910604068631,
 117.46515603769485,
 150.65561534406876,
 138.4290617577104,
 162.53531782086625,
 241.72594354882554,
 297.6174351362668,
 258.9902565673466,
 231.39077110837846,
 77.35978559439005,
 115.57234379751064,
 169.02292657811248,
 125.71770592700935,
 147.83556599695487,
 48.289099940359215,
 254.2586110583671,
 118.37838685625852,
 101.40040584504581,
 220.24323846381753,
 109.90740885581828,
 265.93936416185176,
 107.44144993958338,
 120.06210895898839,
 118.93670481491405,
 61.17679582521464,
 53.279724852048545,
 85.24592952352623,
 64.1342421388138,
 54.43129901554803,
 107.43140585973916,
 50.17874479418551,
 112.02678386060182,
 194.67737630808568,
 85.04718952687385,
 112.49049179366227,
 87.99264156564458,
 53.59141220307597,
 249.85250969602046,
 324.1541228512758,
 104.13980641527043,
 25.692716795426673,
 182.83368262513883,
 173.31833609774242,
 228.9390775272103,
 36.47587447587789,
 113.74420982397302,
 208.006386791656,
 237.48166663247926,
 116.74062658706264,
 71.21866030191806,
 100.72856967181654,
 71.94270058901041,
 237.366675669227,
 62.61955989984279,
 162.9161882794647,
 120.49094646843804,
 69.19350451436898,
 148.3973180312232,
 209.37327583206505,
 99.14008729878141,
 129.87264152434105,
 143.16352441900136,
 84.31863717162416,
 63.762898457018096,
 108.08621460838565,
 120.05422904204583,
 206.1539143506618,
 92.40571761693104,
 245.72360805388644,
 160.61207069632096,
 208.44022187891184,
 213.29698697642215,
 162.3918569004924,
 256.55670804851314,
 154.14459610515055,
 47.40721502566882,
 103.4511167699508,
 244.20839185785567,
 85.48158453193295,
 150.11140657458378,
 95.5309047984473,
 276.0937278492215,
 56.50876764777304,
 193.9061205859681,
 230.43288613492214,
 126.1766640366197,
 140.04337290011264,
 179.8167005187783,
 94.11678603097324,
 98.38095911643676,
 86.50003206461835,
 246.0582737059049,
 231.16038731759383,
 93.44951916660673,
 48.635345409280276,
 160.84776127786174,
 114.61257762143735,
 112.83741431644027,
 96.15378581023215,
 164.26372273758437,
 55.40612313093201,
 149.06361378290813,
 113.73816510279212,
 180.45662574768485,
 126.61937660922992,
 200.24876566880505,
 164.45635230640985,
 127.78558747957455,
 61.54116673512129,
 243.7784511152288,
 120.70138087913493,
 153.1384340493594,
 80.46520619286325,
 156.47467896023946,
 219.58114032942353,
 84.66389748298857,
 163.69063519795506,
 52.61215851977563,
 154.03081411899376,
 165.4830490945825,
 112.15393605045699,
 173.7092094393386,
 132.42205729817067,
 168.9968091847003,
 148.52197651808973,
 139.6718525894892,
 72.15590878715338,
 111.66433453820427,
 61.32532064473857,
 29.00319500899858,
 82.74142483393672,
 145.5241424478083,
 225.33203037686408,
 53.985215084039446,
 145.50197289294738,
 135.09551322579148,
 167.1682027769635,
 215.44761211976797,
 158.17421021263232,
 67.88059149955897,
 242.34203303570763,
 53.63760319113821,
 282.267745994437,
 138.61548724601445,
 112.29688113598704,
 130.24267811589257,
 91.33743995257366,
 54.390169668148665,
 149.83907588800056,
 33.69032784242385,
 150.07635729414545,
 164.020257132831,
 126.07749482663431,
 89.50316451215566,
 64.77158706176651,
 149.08892970824493,
 248.66924211988902,
 117.56180453097852,
 91.39572541147643,
 182.47892928856194,
 225.9538573435293,
 110.51041711137461,
 128.29447901476507,
 176.2330538114516,
 212.8430365734336,
 232.44275445896352,
 132.7550173609269,
 99.19823918885858,
 195.48822094052113,
 77.72896006045623,
 109.8430795726795,
 93.34814076584493,
 214.27542061622466,
 97.12799406607758,
 125.39604574184148,
 84.47355783971692,
 123.45174502500966,
 106.42664207481131,
 199.75272997954244,
 88.3956658202765,
 141.5638951030594,
 186.50698321599114,
 69.79301212041217,
 67.52769060592847,
 58.404693034293054,
 64.11820823432295,
 108.5340875336408,
 109.99243832618676,
 219.66028644174622,
 84.70113868177924,
 106.46343576096912,
 40.852329282551324,
 259.70101412876693,
 132.10667473784204,
 83.65483143686322,
 87.24313960799441,
 120.18724635413692,
 63.12020376163246,
 39.613551947281884,
 153.97257985855794,
 73.97227312966663,
 75.63307058760738,
 113.62660642521188,
 221.1906239600585,
 138.4696510072153,
 132.4057441456374,
 222.78522951432396,
 72.26008449178565,
 166.9799825106291,
 38.599556696418155,
 238.01668949107332,
 139.77761898794813,
 100.15422329402791,
 89.78749091933686,
 97.58204536527198,
 78.87971728106028,
 49.55739370759927,
 135.27868026171012,
 128.81907903777295,
 122.61739275800151,
 107.6243850092069,
 97.57360047497478,
 65.98383664754573,
 121.74021427663087,
 158.50481824408365,
 41.77624386598201,
 144.06374675712138,
 67.24248629110912,
 112.80935961408521,
 209.12184596201323,
 98.14754708942041,
 58.52178373511867,
 332.9151181390686,
 135.33063647648302,
 28.265708330590265,
 128.2734818181451,
 111.24972935252471,
 172.32068729363286,
 237.06198791737998,
 199.6809681634432,
 157.80142484090567,
 114.7474584024849,
 66.4802675358636,
 246.5800924209211,
 167.1209134247716,
 83.58219931564375,
 45.44762171456279,
 232.75407728153763,
 190.33113578327115,
 142.40863325915325,
 75.23638836560404,
 99.32268885999815,
 148.90824324922377,
 172.558960416114,
 107.3147113938252,
 211.36241591605165,
 191.55902769937518,
 43.110653426850305,
 177.70288945627757,
 272.7789713703203,
 87.20270258134204,
 153.6983873378963,
 113.14550484080222,
 283.3077298944736,
 91.91590118733536,
 148.41685267115054,
 111.56295901696046,
 105.87464307996508,
 23.045238282777632,
 154.36845736036878,
 177.49249107252396,
 56.73298627430077,
 172.2392680428885,
 80.80842377667071,
 86.27921993591505,
 84.43071007814633,
 127.21409830482625,
 212.53068543497432,
 36.6021183391071,
 127.91660822911152,
 113.91622095127629,
 80.56219410523772,
 103.13454224308168,
 67.76310723808346,
 78.63527364637322,
 55.223639834132626,
 214.66284079672477,
 145.5777145872609,
 86.04876557940851,
 107.13668106489017,
 142.77942412592228,
 28.35879920976909,
 149.96206530012847,
 212.36027410655223,
 116.10289089484378,
 141.90213464821448,
 109.84864192246528,
 125.8968662506339,
 116.091012019062,
 114.15962070841863,
 131.34617488385416,
 128.54999480062222,
 163.1306840381355,
 149.20491600061308,
 212.08959458099307,
 132.24171215679263,
 255.01776421273087,
 41.46304827264874,
 116.11518979526323,
 106.61977677569955,
 58.41125200507175,
 72.36406736316029,
 191.2830793164675,
 138.3953679004106,
 203.50168940718896,
 198.68567689335333,
 52.822670339353344,
 141.53616604253486,
 175.45790015482345,
 92.9323210411211,
 151.79244317791316,
 65.86606146620579,
 105.4093550491606,
 177.3857494735414,
 37.558961245487076,
 51.79310094008661,
 56.56577492547945,
 207.14713056233725,
 77.69347220783739,
 175.7891409338472,
 41.72851393495818,
 77.80979328844154,
 87.76768871059554,
 179.81964694537692,
 97.80559432532478,
 131.74487238985813,
 135.41237020054703,
 79.96592724685932,
 133.49040505957723,
 188.06102790014734,
 109.58358058253982,
 56.551111804190015,
 59.37746788513299,
 27.434283593525812,
 148.11784042113226,
 269.12925969366466,
 90.92598799545705,
 154.7374203491838,
 20.772758162555114,
 157.3345409798497,
 117.19280522007311,
 88.15680629395555,
 85.81206864299449,
 123.51745427359648,
 199.6010855403848,
 262.48040682628107,
 39.224820229033554,
 278.25314476355874,
 27.459916885708157,
 104.9598325062021,
 178.9064528863618,
 134.86163319695487,
 77.44337318660648,
 112.81083995897734,
 158.49591652481146,
 101.80937696705544,
 55.091748060213156,
 68.0150767464832,
 124.90097952746407,
 269.3825793444149,
 83.60412007682396,
 218.53513242236363,
 190.9410517128781,
 131.01159845090052,
 134.48434982606713,
 100.02207007990786,
 70.22091023776322,
 150.94666450266462,
 97.59669041970633,
 241.78394239332766,
 267.55688391274856,
 132.08180393771127,
 33.72124857430401,
 331.2415962712563,
 107.82545283127726,
 148.11667477833143,
 111.73675260146052,
 62.379900589612994,
 127.09993924046542,
 207.6470630296032,
 47.12040664340664,
 82.5253038010161,
 185.24284037454728,
 223.75947778319917,
 182.65307051402118,
 227.10630938991986,
 222.19869383515737,
 73.4412150905743,
 112.75621287827114,
 149.37582717056333,
 137.18418098709486,
 300.18638092791616,
 87.994910604023,
 95.90894900279118,
 77.47171703221764,
 69.61333348030391,
 145.05101743314316,
 145.9559469202266,
 68.24757097523691,
 48.12336769657751,
 148.4433375501575,
 95.98763715447942,
 80.57085604981492,
 287.26537091506526,
 106.92123696763893,
 76.04718703969267,
 174.6585957022442,
 276.7408063452334,
 169.50067662735154,
 212.95720000277052,
 160.879252659751,
 97.25743395597068,
 153.59011889685485,
 85.55171999223627,
 176.35791780478698,
 65.76256065155917,
 150.3199156833518,
 127.02429297173828,
 239.7549000585389,
 198.88419105665486,
 74.50509249601666,
 95.5494306650228,
 68.80694128596328,
 279.759570023011,
 165.82509598251406,
 153.66453047831175,
 246.3543835045157,
 112.51279002113492,
 144.5521463376798,
 161.12507566462148,
 212.5940748541219,
 36.38024041358166,
 106.56493101297443,
 58.79385995425032,
 105.7000790637358,
 72.89082609594982,
 173.53363951966202,
 119.74206140554787,
 49.80447845304677,
 140.8012892134159,
 166.12792596002635,
 54.65733278280234,
 221.2707129128254,
 244.54160522870131,
 140.7748291227164,
 222.64836695075942,
 63.00506627272127,
 98.27414959281,
 81.54267019285055,
 140.48922893093976,
 80.82030458368739,
 129.76209547845625,
 27.04209572777228,
 75.88409790002119,
 212.23159964588214,
 87.16898386450309,
 98.12883220888752,
 133.5033251095642,
 89.94148191296384,
 164.33175033486376,
 159.23222371464263,
 71.94571898667772,
 90.41803551465826,
 124.36897060235722,
 74.50519525818316,
 58.69115181379558,
 339.73247074645366,
 247.92888866854543,
 302.2406408208036,
 165.8959209515713,
 149.0884354584218,
 59.77216721041659,
 132.16586459127788,
 152.10317493208353,
 101.65615945170266,
 126.42524394748068,
 46.88145535859569,
 44.43551535224948,
 65.38131393464036,
 32.635841633241206,
 277.0223222039697,
 273.1166141637121,
 259.473430984812,
 196.0557802996892,
 64.37932209785995,
 106.03507960033791,
 35.907840029442035,
 104.66534920526469,
 109.06652706527333,
 146.126724707666,
 77.40793992853705,
 97.18229275758006,
 163.53968420625006,
 238.50220495431483,
 79.00459804264558,
 54.70266162893721,
 93.64229370781132,
 86.66598351008312,
 73.8130910970405,
 242.72018188893978,
 86.56594985212142,
 103.9254536690603,
 76.40293133794017,
 91.94649403169214,
 48.01532481874927,
 160.69490572961544,
 79.5095785919533,
 165.34948271415908,
 104.7273961414586,
 132.5702184203149,
 131.99270145712603,
 245.2978241103251,
 144.35458292291935,
 135.08300733667429,
 160.8661423802411,
 182.50693648894554,
 110.62404793759808,
 219.8454386622793,
 39.33276304100692,
 116.27728938502995,
 223.89342794950457,
 112.16416815409457,
 44.112393433138486,
 134.2025829549491,
 243.5390363736171,
 103.71781388358511,
 78.80675222663348,
 76.63337605345336,
 162.8727641422285,
 236.18350349751356,
 75.97008677854726,
 118.5292194474004,
 42.64019905957288,
 62.18621346222971,
 101.63206462863971,
 86.5721080500527,
 99.4570351380434,
 229.4414474414333,
 137.5396294627843,
 156.07372849220974,
 142.2172718909697,
 51.184796813507035,
 235.58010861176288,
 107.27843838749703,
 70.54871214593503,
 78.95362081215782,
 143.97491529169238,
 188.84869819365977,
 177.48493171015954,
 90.29508829100284,
 116.803309863762,
 99.38115978056403,
 171.18923609412482,
 76.29546177748713,
 265.59237486676835,
 121.45353192493003,
 157.85233913382467,
 229.30198464197818,
 155.9560495264291,
 137.02434287968688,
 173.19421108625426,
 163.43952090339104,
 105.46662651237119,
 66.33388489226303,
 231.0864250016214,
 154.34977342629952,
 105.40447702507706,
 267.8133758598513,
 120.25307246116417,
 159.3496217362627,
 63.42901716982535,
 151.19042566588004,
 238.93990738723406,
 65.46679833533942,
 208.95975720741063,
 84.3364216697033,
 145.7746096975396,
 58.53550978551396,
 81.44620921663574,
 56.16383122838042,
 181.37958620048727,
 200.7361547144659,
 61.12706784543162,
 91.71181671594996,
 58.61463494930254,
 57.0253262237052,
 105.39653346614394,
 61.06743284124526,
 49.91746805057324,
 58.69938923327908,
 158.92468624162828,
 237.97448568268823,
 40.52705316661945,
 146.22955120104828,
 216.75646131423625,
 117.03689574634147,
 107.89509463270329,
 111.93202609467944,
 114.04848824666638,
 54.00339107250581,
 189.4677937953572,
 208.94331778791104,
 102.66061720659971,
 151.28692420209356,
 128.60776599828642,
 130.2347404591033,
 287.39171512023444,
 52.23093686829674,
 86.23382882233629,
 232.1718411175438,
 125.58127606402954,
 68.6155600469019,
 170.9104172947629,
 126.09765279730625,
 182.55548168523998,
 229.55257234472455,
 228.30405244154124,
 45.45521105120952,
 227.69348341217412,
 100.47967087530691,
 226.14546842720506,
 179.45447517518195,
 160.43176356629007,
 53.77670105668439,
 258.92791809383937,
 57.23328535397911,
 54.329149195436514,
 125.23166157581716,
 39.96342148790566,
 94.00451854480185,
 89.82418103345,
 39.78410744832665,
 153.51926676196052,
 53.08142082263813,
 186.40450234516865,
 58.21016830640502,
 138.65310369245256,
 56.33217422459388,
 232.04861828843107,
 116.766052683175,
 128.10112203735767,
 242.94927163303043,
 55.343486069726396,
 76.85447389670948,
 78.57962861861846,
 59.53918019909242,
 273.67880122961657,
 69.18566501125794,
 69.57484934162632,
 79.5838115159107,
 67.10891101090823,
 118.11826467811825,
 75.8302513748306,
 163.985702578487,
 58.98440706703765,
 178.94543311683034,
 137.81621394251837,
 51.04778069015342,
 158.67224808793756,
 164.08135408025495,
 163.7670295016674,
 118.630309209114,
 79.63872538432544,
 213.85577468705398,
 122.23310425420766,
 115.5932009847465,
 153.4674497443676,
 144.3882553869254,
 79.08831580018632,
 139.64538853177356,
 264.1031993353166,
 138.7929566598392,
 249.46131472943858,
 251.23887583592634,
 54.163864303518814,
 67.78778801251742,
 166.96366742689858,
 171.96128451840548,
 160.1779056445676,
 60.73179803702505,
 213.38504005684183,
 67.97649075239173,
 103.94235524154723,
 199.41208489830802,
 219.6132135705409,
 126.78264082487792,
 92.02848677703008,
 167.20455995064847,
 64.30600979480845,
 82.63461325310357,
 213.86740814247506,
 72.96273427565608,
 162.00438236945936,
 126.92055024183435,
 106.35991048872691,
 147.10659451248267,
 90.1110385740837,
 19.613365017762757,
 69.21438272685815,
 100.44450860226257,
 71.31057647495217,
 259.0461364383958,
 67.76159234204876,
 167.02659530080828,
 187.7738243865209,
 87.09830985294721,
 108.34150254786944,
 82.69550768820515,
 130.1830350684374,
 326.27964541419067,
 225.63339355755832,
 106.45695704955126,
 41.93910679544809,
 67.92530008870038,
 150.63835103890378,
 198.71931445996887,
 122.99939569961309,
 107.68652415985018,
 77.3570003687449,
 309.1358467221328,
 34.529583632589606,
 129.06039791868767,
 33.52966432399823,
 146.2969208112392,
 212.437294437747,
 133.71088719973403,
 152.35938409776406,
 53.5687876507393,
 118.29164264701882,
 103.27094964214282,
 88.45590097568392,
 135.6684998872988,
 102.73486242473876,
 123.47962068248346,
 110.84728806371402,
 220.14333008776347,
 118.98723340388246,
 171.59023024155542,
 194.23063021992692,
 133.45006288994395,
 218.8186914484455,
 113.32116463710561,
 209.01100825442188,
 125.03230142243244,
 173.74258184955696,
 212.43929314533602,
 163.90542644628943,
 139.84638463489145,
 39.49663781741429,
 61.285609379282505,
 169.55756074079974,
 133.6695415127171,
 167.5163529050522,
 322.236015705616,
 100.46555052768088,
 47.217242603841235,
 156.4233844592617,
 111.42922319701415,
 115.2641855889764,
 218.92816791587146,
 202.87693907248305,
 78.67270079868875,
 127.64134439064011,
 296.5148649878282,
 88.22090868666,
 84.88448681596657,
 74.12733725886828,
 139.5815964030359,
 80.05931011062985,
 259.6279530443323,
 175.3740997451448,
 136.215197707341,
 65.80364570249888,
 149.89619527769875,
 80.72446226473113,
 88.97088900241471,
 130.0451461586706,
 157.01039429986793,
 99.81940892777315,
 140.76171737905162,
 107.34151719847264,
 222.42289709348722,
 122.63920031886214,
 200.65227067945185,
 47.238077741161305,
 94.91812638753464,
 64.84861661739593,
 66.54824138412674,
 92.69678212608031,
 254.0934328716899,
 132.96954961554167,
 54.2761911126785,
 162.81788466716426,
 65.31535885877072,
 71.40702600963016,
 92.77814813898799,
 88.73470765309366,
 71.13169788448747,
 137.70438888423274,
 76.6271206468702,
 23.47477729329929,
 46.839885437199776,
 96.96059607551925,
 105.33649271890533,
 120.04020373691473,
 79.15132905106522,
 64.59275845015446,
 80.59660906533227,
 69.94246144045833,
 283.3877818476477,
 261.9863088051358,
 40.79080804862782,
 224.02239831550327,
 179.46373024934593,
 210.6889148317253,
 272.91073770379575,
 123.11415627063363,
 134.33122495131204,
 95.96636356593906,
 162.04573804852134,
 62.82623886713258,
 102.29408918422413,
 135.3289590291376,
 87.14014309237736,
 94.95536789839738,
 102.42129280276637,
 146.45802883194895,
 232.25544691903352,
 56.35071217943922,
 157.58288244308136,
 197.97771966428442,
 39.26382828991589,
 133.98824866140313,
 83.99887953812241,
 167.5998236895254,
 53.230071877182354,
 161.52966550940417,
 77.10544707930822,
 172.52982534611226,
 155.77900053476398,
 210.8932508568968,
 137.32536113802868,
 51.104107479732,
 46.07968476487225,
 51.09693272702384,
 165.46606207905597,
 54.85594511737083,
 63.04126148031938,
 63.696369351714225,
 203.97707861848107,
 315.60397131552384,
 162.2170912561312,
 261.18986906114867,
 97.2613165306228,
 145.98009470691545,
 72.91786918472043,
 127.02755437573376,
 137.2840980953366,
 82.48612464354233,
 67.88922349217141,
 81.4681478959722,
 73.04864933809523,
 107.04645623452464,
 180.22593021710279,
 88.43380217569523,
 90.70674678208893,
 99.54758744248902,
 132.34636453484472,
 247.5165146475887,
 144.83265894227725,
 46.404794107182504,
 211.89308637055626,
 144.84532243382938,
 43.2106044241457,
 53.82748899187105,
 138.2517371575128,
 151.81334657796066,
 265.4665378930459,
 119.1614648881508,
 109.85012274745075,
 157.70293145515714,
 143.06621111481914,
 66.46895015606911,
 201.73697657457345,

In [36]:
df.insert(10, 'Distances', distances)
df.head()

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,Distances,class
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,0.000000,g
1,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,128.041496,g
2,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,284.537502,g
3,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,54.515743,g
4,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,284.727263,g

In [38]:
df_sorted = df.sort_values(by='Distances')
df_sorted

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,Distances,class
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,0.000000,g
17788,33.2724,11.1166,2.7903,0.4457,0.2796,29.6062,16.6947,-7.4326,36.4037,84.3813,9.811468,h
16368,34.8773,10.9165,2.7528,0.4170,0.2677,31.9997,25.0411,-7.3443,34.4381,86.9540,12.204103,h
16559,24.8882,7.8008,2.4232,0.6792,0.4472,25.3809,14.8384,-9.8301,38.8998,77.8319,12.650584,h
6038,21.7287,11.3452,2.3598,0.5939,0.3079,20.9225,20.1144,-9.9040,35.7407,75.2580,13.675918,g
...,...,...,...,...,...,...,...,...,...,...,...,...
12636,303.5676,38.3100,3.5777,0.1476,0.0812,-449.9526,200.3148,-19.2293,71.5012,86.0291,580.575217,h
15355,276.2766,35.8288,3.5838,0.0604,0.0572,-457.9161,-169.1552,15.1931,68.1382,187.0187,588.554009,h
18979,265.5424,69.4251,3.2266,0.2337,0.1531,464.6310,-287.3636,42.0901,74.8054,145.7859,594.425684,h
12663,265.5827,76.4762,3.1605,0.2898,0.1615,473.0654,-284.7038,40.4617,77.5514,175.0569,603.822656,h
17121,222.9085,110.8744,3.9151,0.0373,0.0290,575.2407,-264.2232,-97.7706,37.7030,192.7844,669.880280,h

In [44]:
df_sorted.drop(0, inplace=True)
df_sorted

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,Distances,class
17788,33.2724,11.1166,2.7903,0.4457,0.2796,29.6062,16.6947,-7.4326,36.4037,84.3813,9.811468,h
16368,34.8773,10.9165,2.7528,0.4170,0.2677,31.9997,25.0411,-7.3443,34.4381,86.9540,12.204103,h
16559,24.8882,7.8008,2.4232,0.6792,0.4472,25.3809,14.8384,-9.8301,38.8998,77.8319,12.650584,h
6038,21.7287,11.3452,2.3598,0.5939,0.3079,20.9225,20.1144,-9.9040,35.7407,75.2580,13.675918,g
17042,30.2128,22.8856,2.6758,0.3291,0.2120,16.9338,25.8419,-12.6206,39.7337,83.5209,14.223855,h
...,...,...,...,...,...,...,...,...,...,...,...,...
12636,303.5676,38.3100,3.5777,0.1476,0.0812,-449.9526,200.3148,-19.2293,71.5012,86.0291,580.575217,h
15355,276.2766,35.8288,3.5838,0.0604,0.0572,-457.9161,-169.1552,15.1931,68.1382,187.0187,588.554009,h
18979,265.5424,69.4251,3.2266,0.2337,0.1531,464.6310,-287.3636,42.0901,74.8054,145.7859,594.425684,h
12663,265.5827,76.4762,3.1605,0.2898,0.1615,473.0654,-284.7038,40.4617,77.5514,175.0569,603.822656,h
17121,222.9085,110.8744,3.9151,0.0373,0.0290,575.2407,-264.2232,-97.7706,37.7030,192.7844,669.880280,h

In [73]:
K = 7
df_k = df_sorted[:K]
print("Highest class: {}".format(df_k['class'].value_counts().idxmax()))
df_k

Highest class: h

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,Distances,class
17788,33.2724,11.1166,2.7903,0.4457,0.2796,29.6062,16.6947,-7.4326,36.4037,84.3813,9.811468,h
16368,34.8773,10.9165,2.7528,0.4170,0.2677,31.9997,25.0411,-7.3443,34.4381,86.9540,12.204103,h
16559,24.8882,7.8008,2.4232,0.6792,0.4472,25.3809,14.8384,-9.8301,38.8998,77.8319,12.650584,h
6038,21.7287,11.3452,2.3598,0.5939,0.3079,20.9225,20.1144,-9.9040,35.7407,75.2580,13.675918,g
17042,30.2128,22.8856,2.6758,0.3291,0.2120,16.9338,25.8419,-12.6206,39.7337,83.5209,14.223855,h
8116,21.7358,10.5355,2.2695,0.5753,0.2930,17.5263,16.8871,-4.7663,41.1555,80.2342,15.011597,g
3745,23.1200,13.0592,2.3847,0.4660,0.2577,24.7351,14.5916,2.8713,42.4620,77.5756,15.862067,g

**With standarization**

In [76]:
# Separate numerical features and categorical label
numerical_features = df.iloc[:, :-1]  # All columns except the last (label)
categorical_label = df.iloc[:, -1]

# Create a StandardScaler object
scaler = StandardScaler()

# Standardize the numerical features
scaled_features = scaler.fit_transform(numerical_features)

# Reconstruct the DataFrame with standardized features and original label
df_standardized = pd.DataFrame(scaled_features, columns=numerical_features.columns)
df_standardized['label'] = categorical_label
df_standardized.head()

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,label
0,-0.577226,-0.336804,-0.381130,0.062759,-0.148923,0.541042,0.224818,-0.405842,0.476816,-1.497866,g
1,-0.510969,-0.570027,-0.648595,0.820383,1.471776,0.516919,0.260364,-0.490094,-0.815418,0.153125,g
2,2.568278,6.205858,2.615783,-1.875883,-1.773241,2.044992,-1.478536,-2.183030,1.889224,0.842635,g
3,-0.694768,-0.687259,-1.029478,1.282069,1.606608,0.532771,-0.333515,-0.355359,-0.658804,-1.031463,g
4,0.516622,0.476384,0.711157,-0.347506,-0.284660,-0.020200,0.353086,1.036620,-0.881039,2.176427,g

In [77]:
df_standardized.describe()

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist
count,1.902000e+04,1.902000e+04,1.902000e+04,1.902000e+04,1.902000e+04,1.902000e+04,1.902000e+04,1.902000e+04,1.902000e+04,1.902000e+04
mean,7.172671e-17,-1.195445e-16,-2.241460e-16,-3.025971e-16,1.128201e-16,-5.977226e-18,4.184058e-17,-9.712992e-18,1.195445e-17,-8.965839e-18
std,1.000026e+00,1.000026e+00,1.000026e+00,1.000026e+00,1.000026e+00,1.000026e+00,1.000026e+00,1.000026e+00,1.000026e+00,1.000026e+00
min,-1.155862e+00,-1.209064e+00,-1.869959e+00,-2.008809e+00,-1.939745e+00,-7.661315e+00,-6.712427e+00,-9.897993e+00,-1.059103e+00,-2.576420e+00
25%,-6.825213e-01,-5.623790e-01,-7.361978e-01,-7.905934e-01,-7.798731e-01,-2.745535e-01,-4.586055e-01,-5.329216e-01,-8.465631e-01,-6.868179e-01
50%,-3.800999e-01,-2.747838e-01,-1.807437e-01,-1.431941e-01,-1.643062e-01,1.409487e-01,9.350332e-02,1.999694e-02,-3.818041e-01,-2.631582e-02
75%,3.982656e-01,1.394619e-01,5.852541e-01,6.748758e-01,6.385776e-01,4.796163e-01,4.959385e-01,5.136004e-01,6.986894e-01,6.255307e-01
max,6.631304e+00,1.276608e+01,5.286407e+00,2.804429e+00,4.167511e+00,9.789330e+00,4.466292e+00,8.623528e+00,2.388785e+00,4.037785e+00

---

In [13]:
# Shuffle the dataset
df_shuffled = df.sample(frac=1)
df_shuffled.reset_index(drop=True, inplace=True)
df_shuffled.head(10)

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,13.2353,10.2651,2.1804,0.7987,0.4917,13.0601,6.6590,10.9489,25.9380,197.8260,g
1,42.9187,19.7107,3.0238,0.2887,0.1236,-8.7055,-29.7166,-15.8674,63.1147,102.2467,h
2,20.5434,8.9884,2.4346,0.6287,0.3438,24.4636,9.6247,-3.3060,39.6377,235.6280,h
3,26.0564,17.3963,2.6848,0.4008,0.2593,-0.9388,14.4535,-9.3874,62.6010,122.5500,g
4,153.3440,40.1891,3.0958,0.2447,0.1504,177.5813,-84.6800,-19.4847,2.1684,199.6500,h
5,56.6984,11.2842,2.8735,0.3346,0.1884,-18.5883,29.1725,-5.3136,24.6332,120.1266,h
6,39.9538,24.8292,3.3153,0.2385,0.1362,19.2151,33.1294,13.6998,0.1390,127.1640,g
7,39.0165,23.3996,3.1053,0.2370,0.1377,8.3237,-22.4536,-21.3361,3.2298,139.1020,g
8,36.6913,28.2534,2.7623,0.3509,0.1858,-28.6774,-34.1515,18.7668,69.1250,105.1440,g
9,21.1380,12.1025,2.6004,0.5521,0.3375,16.3835,16.7364,-4.3067,10.2100,97.0489,h

In [16]:
# Splitting the dataset with 80/20 ratio
LENGTH = len(df)
TRAIN_SIZE = .8
df_train = df_shuffled[:int(LENGTH * TRAIN_SIZE)]
df_test = df_shuffled[int(LENGTH * TRAIN_SIZE):]
print("Train dataset: ")
print("Length : {}".format(len(df_train)))
display(df_train.head())
print("\nTest dataset: ")
print("Length : {}".format(len(df_test)))
display(df_test.head())

Train dataset:
Length : 15216

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,13.2353,10.2651,2.1804,0.7987,0.4917,13.0601,6.6590,10.9489,25.9380,197.8260,g
1,42.9187,19.7107,3.0238,0.2887,0.1236,-8.7055,-29.7166,-15.8674,63.1147,102.2467,h
2,20.5434,8.9884,2.4346,0.6287,0.3438,24.4636,9.6247,-3.3060,39.6377,235.6280,h
3,26.0564,17.3963,2.6848,0.4008,0.2593,-0.9388,14.4535,-9.3874,62.6010,122.5500,g
4,153.3440,40.1891,3.0958,0.2447,0.1504,177.5813,-84.6800,-19.4847,2.1684,199.6500,h

Test dataset:
Length : 3804

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
15216,32.0093,14.5778,2.6590,0.3487,0.1941,-29.9439,-25.0603,10.5972,72.0623,250.4140,h
15217,34.7886,19.5066,3.0282,0.2605,0.1429,-19.2971,-17.9780,10.9297,14.0540,221.1710,g
15218,64.3192,26.8663,3.4539,0.1762,0.0891,6.8989,64.5494,-21.5750,7.6530,245.0970,g
15219,105.5703,30.1647,3.2129,0.2940,0.1617,-161.2025,78.1421,-23.5357,49.2844,237.1594,h
15220,19.2295,11.4438,2.3655,0.5991,0.3039,-10.4220,-18.4222,8.9212,24.2620,222.8380,g

In [62]:
# Separating features from column
x = df_train[df_train.columns[:-1]].values
y = df_train[df_train.columns[-1:]].values
print(x)
print(y)

[[ 13.2353  10.2651   2.1804 ...  10.9489  25.938  197.826 ]
 [ 42.9187  19.7107   3.0238 ... -15.8674  63.1147 102.2467]
 [ 20.5434   8.9884   2.4346 ...  -3.306   39.6377 235.628 ]
 ...
 [128.1116  85.0757   3.4305 ... -20.4238   2.8948 328.6118]
 [ 42.6021  12.401    2.2516 ...  -8.6619   6.8576 187.296 ]
 [ 26.1559   9.9788   2.3701 ...   5.9681  61.282   95.2881]]
[['g']
 ['h']
 ['h']
 ...
 ['h']
 ['g']
 ['g']]

In [63]:
# Performing standarization
scaler = StandardScaler()
x = scaler.fit_transform(x)
x

array([[-0.94539759, -0.64989048, -1.36460104, ...,  0.514308  ,
        -0.06310968,  0.05446809],
       [-0.24396917, -0.13208123,  0.42389071, ..., -0.77923321,
         1.36016745, -1.22359322],
       [-0.77270481, -0.71987937, -0.82555124, ..., -0.17330739,
         0.46137123,  0.55994652],
       ...,
       [ 1.76916684,  3.45123811,  1.28632799, ..., -0.99902085,
        -0.94529825,  1.80330149],
       [-0.25145053, -0.53280011, -1.2136162 , ..., -0.43166061,
        -0.79358595, -0.0863363 ],
       [-0.6400796 , -0.66558549, -0.96232823, ...,  0.27404853,
         1.29000415, -1.3166418 ]])

In [ ]:
# Separating features from column
features = df.iloc[:, :-1]
label = df.iloc[:, -1]

In [57]:
# Define a range of K values to explore
k_values = range(1, 11, 2)  # Example range from 1 to 10

# Initialize variables to store errors
errors = {k: [] for k in k_values}
errors

{1: [], 3: [], 5: [], 7: [], 9: []}

In [ ]:
# K = 7
# df_k = df_sorted[:K]
# df_k['class'].value_counts().idxmax()

In [ ]:
# distances = []
# for x in features:
#     distances.append(np.linalg.norm(x - sample))
# distances

In [ ]:
# Finding the optimal K
for i in range(len(df_train)):
    # Data validation 
    val_features = x[i]
    val_label = y[i]

    # Data training
    train_features = np.delete(x, i, axis=0)
    train_label = np.delete(y, i)

    for k in k_values:
        distances = []
        for x in train_features:
            distances.append(np.linalg.norm(x-val_features))
        distances = distances.sort()

In [ ]:
def scale_dataset(df, oversample=False):
    scaler = StandardScaler()
    x = df[df.columns[:-1]].values
    y = df[df.columns[-1]].values  # Label data (1d array)
    x = scaler.fit_transform(x)    
    return data, x, y

In [20]:
x = df_train[df_train.columns[:-1]].values
x

array([[ 13.2353,  10.2651,   2.1804, ...,  10.9489,  25.938 , 197.826 ],
       [ 42.9187,  19.7107,   3.0238, ..., -15.8674,  63.1147, 102.2467],
       [ 20.5434,   8.9884,   2.4346, ...,  -3.306 ,  39.6377, 235.628 ],
       ...,
       [128.1116,  85.0757,   3.4305, ..., -20.4238,   2.8948, 328.6118],
       [ 42.6021,  12.401 ,   2.2516, ...,  -8.6619,   6.8576, 187.296 ],
       [ 26.1559,   9.9788,   2.3701, ...,   5.9681,  61.282 ,  95.2881]])

In [17]:
def find_k(df, k_start, k_end):
    best_k = 0
    scaler = StandardScaler()
    return best_k

fLength     32.0093
fWidth      14.5778
fSize         2.659
fConc        0.3487
fConc1       0.1941
fAsym      -29.9439
fM3Long    -25.0603
fM3Trans    10.5972
fAlpha      72.0623
fDist       250.414
class             h
Name: 15216, dtype: object

In [ ]:
def knn(df, k):

## 3) Menerapkan Algoritma K-Nearest Neigbhors